theme: minima
author: Wayne Whitley
description: ............also modified in config (previously blank), added show_excerpts config
github_username:  twaynew
rss: RSS feed
show_excerpts: true
title: Wayne's blog
