theme: minima
title: title modified from config!
author: modified from config Wayne Whitley
description: ............also modified in config (previously blank), added show_excerpts config
github_username:  twaynew
rss: RSS feed
show_excerpts: true
